FROM maven:3.8.5-openjdk-17 AS build
WORKDIR /app
COPY . .
# Maven busca el pom.xml automáticamente
RUN mvn clean package -DskipTests -f $(find . -name "pom.xml" | head -n 1)

FROM amazoncorretto:17-alpine-jdk
WORKDIR /app
RUN apk add --no-cache findutils
COPY --from=build /app/**/target/*.jar app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "app.jar"]
