
FROM maven:3.8.5-openjdk-17 AS build

WORKDIR /app

COPY pom.xml .

RUN build-descarga-dependencias-cache: mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

# Usamos una imagen de JRE (Java Runtime Environment) mucho más ligera
FROM openjdk:17-jdk-slim

RUN addgroup --system spring && adduser --system spring --ingroup spring

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

RUN chown spring:spring app.jar

USER spring

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
